### ISSUE TITLE
Issues while acquiring data using RPC

### ISSUE THREAD

**Issue by dansan566** [habanoz/tezos-reward-distributor#142]
**Describe the bug**
Here is a collection of bugs that I collected together with another Tezos Baker (Bake'n'Rolls).

**To Reproduce**

1. Issue: _"The first issue we experienced is when TezRPC returned 502 on one of the requests (for calculation). This time, TRD paid rewards for some guys, and didn't paid for other guys (probably because the calculation step was failed) - final payments file was OK - it didn't contain failed guys. But we were forced to exclude paid accounts in config in order to pay to the failed accounts. I think the workaround here is to make sure TRD can handle 502 responses during a calculation of rewards and retry. Or simply drop the entire payout."_
2. Issue: **RPC** Payouts cannot be executed currently: 
![Bildschirmfoto 2019-12-04 um 06 59 26](https://user-images.githubusercontent.com/20326784/70806793-6001a880-1dbc-11ea-8771-ede1fb4e26be.png)

**Comment by amzid** [comment]
Can you please split this issue into two issues in order to reference them for PRs?
I would suggest that you keep issue 2 and 4 here and rename the issue to 'Issuess while acquiring data using RPC' (or so). Issue 1 and 3 are related to batch payments and can be moved to a second issue with that name.
I will do a PR for RPC-related issues and reference this one.

**Comment by amzid** [comment]
For the last issue, the rpc command for the raw context (to acquire the chosen snapshot) was causing trouble, slowing down the process and sometimes even leading to a timeout which results in this exception that the API call (not tzstats call, this was a mistake reporting the error and was adjusted in new version) has failed.
This command was replaced with a new one which should be faster than this one and will much less likely lead to a timeout.

**Comment by amzid** [comment]
Concerning issue 2: this should have been fixed by this commit https://github.com/habanoz/tezos-reward-distributor/commit/4494abf7e2f874d18f57757560d21f10dbb953bc. Now the rpc call concerning each delegator balance keeps being retried until it succeeds. Can you pull the new version and verify if this problem is solved?

**Comment by dansan566** [comment]
I still have the issues:
2019-12-15 13:10:12,747 - producer  - API provider call failed, will try again.

I've also switched from mainnet-staging to mainnet but still get the same error
2019-12-15 14:17:33,051 - producer  - API provider call failed, will try again.

Unfortunately,

**Comment by amzid** [comment]
Now I did the PR. Can you pull from the branch and try again?
