### ISSUE TITLE
Old Cycle reward calculation

### ISSUE THREAD

**Issue by gaia** [habanoz/tezos-reward-distributor#160]
Is there a reason TRD cannot calculate rewards for any cycle prior to 111 (approximately, 111 works, but 105 doesn't)?

Babylon started on cycle 112, maybe this has something to do with it?

Current version on mainnet.

Thanks

**Comment by utdrmac** [comment]
If you don't have an archive node, then it's not TRD's fault, it's your node. The default mode for tezos-node is to only keep the most recent 7 cycles. Anything after that is purged. Try running your payment for an older cycle against a RPC endpoint which is an archive node.

**Comment by jdsika** [comment]
@amzid isn't there a check if the node is "archive"? It should give feedback to the user that an archive node is needed or RPC

**Comment by gaia** [comment]
I am running this on an archive node, otherwise I would be able to go back to anything that old (and I was able to go back to 111)

**Comment by utdrmac** [comment]
You'll need to turn on verbose logging then and upload your log file so we can see what's not working correctly. Run with `-V -D` for dry run. Zero out/remove `logs/app.log` first then you can gzip that file and upload it.

**Comment by gaia** [comment]
@utdrmac thank you Matthew. I uploaded the log to our shared private folder on keybase keybase://private/utdrmac%2Ceddieb

**Comment by utdrmac** [comment]
Holy crap! That's a freakin' bug in Tezos protocol.
Look here: https://rpc.tzbeta.net/chains/main/blocks/442368/metadata
Then look at 1 element of 'balance_updates':
```
{
    "kind": "freezer",
    "category": "rewards",
    "delegate": "tz1KksC8RvjUWAbXYJuNrUbontHGor26Cztk",
    "level": 102,
    "change": "-623000000"
  }
```
Notice the index "level" which is actually the cycle. Wow! Look at the current head:
```
{
    "kind": "freezer",
    "category": "rewards",
    "delegate": "tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q",
    "cycle": 185,
    "change": "16000000"
  }
```
Yea, so, damn. Simple fix for TRD but damn, Tezos shouldn't have had something like that.

**Comment by utdrmac** [comment]
@gaia Edit this script: src/rpc/rpc_reward_api.py
Go to line 88 and replace with this:
`                    if (("level" in balance_update and int(balance_update["level"]) == cycle) or ("cycle" in balance_update and int(balance_update["cycle"]) == cycle)) and int(balance_update["change"]) < 0:`
It's a very long line, but should take in to account the older "bug" in the protocol

**Comment by gaia** [comment]
fixed! damn but was this a one off or is it present in other cycles? and does it affect anything beyond calc of rewards for TRD or do you think tzscan/tzstats will also be affected?

**Comment by utdrmac** [comment]
Athens (004) was activated at 458753 which seems to have fixed this. 458752 (003) still shows "level". Does not appear that tzstats is affected by this. (tzscan is dead by the way).
